### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/metro-xmlstreambuffer#10]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by Tomas-Kraus** [comment]
Jobs:
- https://jenkins.eclipse.org/metro/job/xmlstreambuffer-master-build/
- https://jenkins.eclipse.org/metro/job/xmlstreambuffer-ee4j8-build/
