### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/metro-xmlstreambuffer#20]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by Tomas-Kraus** [comment]
PR to merge release info: https://github.com/eclipse-ee4j/metro-xmlstreambuffer/pull/21
Release job passed: https://jenkins.eclipse.org/metro/job/nexus-staging/40/console
