### ISSUE TITLE
integrate new version of stax-ex

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/metro-xmlstreambuffer#23]
we need 1.8.1.NEXT (either 1.8.2 or 1.9.0)

**Comment by Tomas-Kraus** [comment]
Created autoupdate job: https://jenkins.eclipse.org/metro/job/xmlstreambuffer-master-dependency-update/
1st run:
 - PR: https://github.com/eclipse-ee4j/metro-xmlstreambuffer/pull/27
 - Issue: https://github.com/eclipse-ee4j/metro-xmlstreambuffer/issues/28

**Comment by Tomas-Kraus** [comment]
Test run, closing.

**Comment by Tomas-Kraus** [comment]
Everything works as exected.
